---
# CIS Benchmark - Oracle Linux 8 - v1.0.1 - 2021/05/20
# 
# Section 1 - Initial Setup

- name: "1.1 | Filesystem Configuration"
  hosts: all
  become: true
  
  tasks:
    - name: "1.1.1.1 | Ensure mounting of cramfs filesytem is disabled"
      block:
        - name: "1.1.1.1 | cramfs | Modprobe Config"
          lineinfile:
            dest: /etc/modprobe.d/cis.conf
            create: true
            regexp: "^(#)?install cramfs(\\s|$)"
            line: "install cramfs /bin/true"
            mode: 0600

        - name: "1.1.1.1 | cramfs | Disable cramfs"
          modprobe:
            name: cramfs
            state: absent
      tags:
        - l1-server
        - l1-workstation
        - automated
        - rule_1.1.1.1
    
    - name: "1.1.1.2 | Ensure mounting of vfat filesytem is limited"
      block:
        - name: "1.1.1.2 | vfat | Modprobe Config"
          lineinfile:
            dest: /etc/modprobe.d/cis.conf
            create: true
            regexp: "^(#)?install vfat(\\s|$)"
            line: "install vfat /bin/true"
            mode: 0600

        - name: "1.1.1.2 | vfat | Disable vfat"
          modprobe:
            name: vfat
            state: absent
      tags:
        - l1-server
        - l1-workstation
        - manual
        - rule_1.1.1.2
    
    - name: "1.1.1.3 | Ensure mounting of squashfs filesytem is disabled"
      block:
        - name: "1.1.1.3 | squashfs | Modprobe Config"
          lineinfile:
            dest: /etc/modprobe.d/cis.conf
            create: true
            regexp: "^(#)?install squashfs(\\s|$)"
            line: "install squashfs /bin/true"
            mode: 0600

        - name: "1.1.1.3 | squashfs | Disable squashfs"
          modprobe:
            name: squashfs
            state: absent
      tags:
        - l1-server
        - l1-workstation
        - automated
        - rule_1.1.1.3
    
    - name: "1.1.1.4 | Ensure mounting of udf filesytem is disabled"
      block:
        - name: "1.1.1.4 | udf | Modprobe Config"
          lineinfile:
            dest: /etc/modprobe.d/cis.conf
            create: true
            regexp: "^(#)?install udf(\\s|$)"
            line: "install udf /bin/true"
            mode: 0600

        - name: "1.1.1.4 | udf | Disable udf"
          modprobe:
            name: squashfs
            state: absent
      tags:
        - l1-server
        - l1-workstation
        - automated
        - rule_1.1.1.4
    
    - name: |
        "1.1.2 | Ensure /tmp is configured"
        "1.1.3 | Ensure nodev option set on /tmp partition"
        "1.1.4 | Ensure nosuid option set on /tmp partition"
        "1.1.5 | Ensure noexec option set on /tmp partition"
      mount: 
        name: /tmp
        src: "{{ item.device }}"
        fstype: "{{ item.fstype }}"
        state: present
        opts: defaults,nodev,nosuid,noexec
      loop: "{{ ansible_mounts }}"
      notify: remount tmp
      when: item.mount == "/tmp"
      tags:
        - l1-server
        - l1-workstation
        - automated
        - rule_1.1.2
        - rule_1.1.3
        - rule_1.1.4
        - rule_1.1.5
    
    - name: "1.1.6 | Ensure separate partition exists for /var"
      mount: 
        name: /var
        src: "{{ item.device }}"
        fstype: "{{ item.fstype }}"
        state: present
        opts: defaults
      loop: "{{ ansible_mounts }}"
      when: item.mount == "/var"
      tags:
        - l2-server
        - l2-workstation
        - automated
        - rule_1.1.6

    - name: |
        "1.1.7 | Ensure seperate partition exists for /var/tmp"
        "1.1.8 | Ensure nodev option set on /var/tmp partition"
        "1.1.9 | Ensure nosuid option set on /var/tmp partition"
        "1.1.10 | Ensure noexec option set on /var/tmp partition"
      mount: 
        name: /var/tmp
        src: "{{ item.device }}"
        fstype: "{{ item.fstype }}"
        state: present
        opts: defaults,nodev,nosuid,noexec
      loop: "{{ ansible_mounts }}"
      notify: remount var_tmp
      when: item.mount == "/var/tmp"
      tags:
        - l1-server
        - l1-workstation
        - automated
        - rule_1.1.7
        - rule_1.1.8
        - rule_1.1.9
        - rule_1.1.10
    
    - name: "1.1.11 | Ensure separate partition exists for /var/log"
      mount: 
        name: /var/log
        src: "{{ item.device }}"
        fstype: "{{ item.fstype }}"
        state: present
        opts: defaults
      loop: "{{ ansible_mounts }}"
      when: item.mount == "/var/log"
      tags:
        - l2-server
        - l2-workstation
        - automated
        - rule_1.1.11

    - name: "1.1.12 | Ensure separate partition exists for /var/log/audit"
      mount: 
        name: /var/log/audit
        src: "{{ item.device }}"
        fstype: "{{ item.fstype }}"
        state: present
        opts: defaults
      loop: "{{ ansible_mounts }}"
      when: item.mount == "/var/log/audit"
      tags:
        - l2-server
        - l2-workstation
        - automated
        - rule_1.1.12
    
    - name: |
        "1.1.13 | Ensure separate partition exists for /homet"
        "1.1.14 | Ensure nodev option set on /home partition"
      mount: 
        name: /home
        src: "{{ item.device }}"
        fstype: "{{ item.fstype }}"
        state: present
        opts: defaults,nodev
      loop: "{{ ansible_mounts }}"
      notify: remount home
      when: item.mount == "/home"
      tags:
        - l2-server
        - l2-workstation
        - automated
        - rule_1.1.13
    
    - name: |
        "1.1.15 | Ensure nodev option set on /dev/shm partition"
        "1.1.16 | Ensure nosuid option set on /dev/shm partition"
        "1.1.17 | Ensure noexec option set on /dev/shm partition"
      mount:
        name: /dev/shm
        src: "tmpfs"
        fstype: "tmpfs"
        state: present
        opts: nodev,nosuid,noexec
      notify: remount dev_shm
      tags: 
        - l1-server
        - l1-workstation
        - automated
        - rule_1.1.15
        - rule_1.1.16
        - rule_1.1.17
    
    - name: |
        "1.1.18 | Ensure nodev option set on removable media partitions"
        "1.1.19 | Ensure nosuid option set on removable media partitions"
        "1.1.20 | Ensure noexec option set on removable media partitions"
      debug:
        msg: ">>> Not applicable <<<"
      changed_when: false
      tags:
        - l1-server
        - l1-workstation
        - manual
        - rule_1.1.18
        - rule_1.1.19
        - rule_1.1.20
    
    - name: "1.1.21 | Ensure sticky bit is set on all world-writable directories"
      shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
      args:
        warn: no
      changed_when: false
      failed_when: false
      tags:
        - l1-server
        - l1-workstation
        - automated
        - rule_1.1.21


  handlers:
    - name: remount tmp
      mount:
        path: /tmp
        state: remounted
    
    - name: remount var_tmp
      mount:
        path: /var/tmp
        state: remounted
    
    - name: remount home
      mount:
        path: /home
        state: remounted
    
    - name: remount dev_shm
      mount:
        path: /dev/shm
        state: remounted
