---
# CIS Benchmark - Oracle Linux 8 - v1.0.1 - 2021/05/20
# 
# Section 1 - Initial Setup

- name: "1.1 | Filesystem Configuration"
  hosts: all
  become: true
  
  tasks:
    - name: "1.1.1.1 | Ensure mounting of cramfs filesytem is disabled"
      block:
        - name: "1.1.1.1 | cramfs | Modprobe Config"
          lineinfile:
            dest: /etc/modprobe.d/cis.conf
            create: true
            regexp: "^(#)?install cramfs(\\s|$)"
            line: "install cramfs /bin/true"
            mode: 0600

        - name: "1.1.1.1 | cramfs | Disable cramfs"
          modprobe:
            name: cramfs
            state: absent
      tags:
        - l1-server
        - l1-workstation
        - automated
        - rule_1.1.1.1
    
    - name: "1.1.1.2 | Ensure mounting of vfat filesytem is limited"
      block:
        - name: "1.1.1.2 | vfat | Modprobe Config"
          lineinfile:
            dest: /etc/modprobe.d/cis.conf
            create: true
            regexp: "^(#)?install vfat(\\s|$)"
            line: "install vfat /bin/true"
            mode: 0600

        - name: "1.1.1.2 | Disable vfat"
          modprobe:
            name: vfat
            state: absent
      tags:
        - l1-server
        - l1-workstation
        - manual
        - rule_1.1.1.2
    
    - name: "1.1.1.3 | Ensure mounting of squashfs filesytem is disabled"
      block:
        - name: "1.1.1.3 | squashfs | Modprobe Config"
          lineinfile:
            dest: /etc/modprobe.d/cis.conf
            create: true
            regexp: "^(#)?install squashfs(\\s|$)"
            line: "install squashfs /bin/true"
            mode: 0600

        - name: "1.1.1.3 | Disable vfat"
          modprobe:
            name: squashfs
            state: absent
      tags:
        - l1-server
        - l1-workstation
        - automated
        - rule_1.1.1.3



